language: cpp
# sudo: required
dist: trusty
compiler:
- gcc
# - clang
os:
# - linux
# - osx
- windows
osx_image: xcode10.3 # OS X 10.14
before_install:
- |-
    case $TRAVIS_OS_NAME in
      linux)
        sudo apt-get update -qq
        sudo apt-get install python bison flex libboost-dev libboost-filesystem-dev libboost-system-dev python
        pyenv install 2.7.12 ; pyenv global 2.7.12
        ;;
      osx)
        brew update
        brew install python bison flex -v -f 2>&1 && brew upgrade boost || true
        curl "https://bootstrap.pypa.io/get-pip.py" | sudo python
        ;;
      windows)
        choco install python
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-i686-toolchain bison flex mingw-w64-i686-boost
        taskkill //IM gpg-agent.exe //F
        export PATH=$PATH:/C/tools/msys64/mingw32/bin:/C/tools/msys64/usr/bin
        export PATH=/C/Python38:/C/Python38/Scripts:$PATH
        ;;
    esac

install:
#- sudo pip install --upgrade pip setuptools
#- CC=gcc sudo pip install requests[security]
- |-
    case $TRAVIS_OS_NAME in
      linux)
        sudo pip install pytest
        ;;
      osx)
        sudo pip install tornado
        sudo pip install --user nose
        sudo pip install pytest --upgrade --ignore-installed six
        ;;
      windows)
        pip install pytest
        ;;
    esac
- pip install pyyaml
- pip install enum34
- pip install pyserial
script:
- |-
  case $TRAVIS_OS_NAME in
    linux)
      make all
      ;;
    osx)
      make all
      ;;
    windows)
      mingw32-make all
      ;;
  esac
- pushd erpcgen/test ; py.test ; popd
- python test/run_unit_tests.py
